"use client";

import { useEffect, useRef } from "react";
import { X, Sparkles } from "lucide-react";

interface AiContextModalProps {
    businessName: string | null;
    summary: string;
    onClose: () => void;
}

export default function AiContextModal({
    businessName,
    summary,
    onClose,
}: AiContextModalProps) {
    const closeRef = useRef<HTMLButtonElement>(null);

    useEffect(() => {
        closeRef.current?.focus();
    }, []);

    useEffect(() => {
        function handleKey(e: KeyboardEvent) {
            if (e.key === "Escape") onClose();
        }
        window.addEventListener("keydown", handleKey);
        return () => window.removeEventListener("keydown", handleKey);
    }, [onClose]);

    return (
        <div
            className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fade-in"
            onClick={(e) => {
                if (e.target === e.currentTarget) onClose();
            }}
        >
            <div className="w-full max-w-lg bg-surface border border-border-bright rounded-xl shadow-2xl shadow-black/80 animate-slide-up">
                {/* Header */}
                <div className="flex items-center justify-between px-5 py-4 border-b border-border">
                    <div className="flex items-center gap-2.5">
                        <div className="p-1.5 rounded-lg bg-amber-500/10 border border-amber-500/20">
                            <Sparkles className="w-3.5 h-3.5 text-amber-400" />
                        </div>
                        <div>
                            <p className="text-text-primary text-sm font-display font-semibold">
                                {businessName || "Business"}
                            </p>
                            <p className="text-text-dim text-xs font-mono">AI Context</p>
                        </div>
                    </div>
                    <button
                        ref={closeRef}
                        onClick={onClose}
                        className="p-1.5 rounded-lg text-text-muted hover:text-text-primary hover:bg-surface-3 transition-all"
                    >
                        <X className="w-4 h-4" />
                    </button>
                </div>

                {/* Body */}
                <div className="p-5">
                    <div className="bg-surface-2 border border-border rounded-lg p-4">
                        <p className="text-text-muted text-sm font-mono leading-relaxed whitespace-pre-wrap">
                            {summary}
                        </p>
                    </div>
                    <p className="mt-3 text-text-dim text-xs font-mono flex items-center gap-1.5">
                        <Sparkles className="w-3 h-3 text-amber-400/60" />
                        Generated by AI — may not reflect current business status
                    </p>
                </div>

                {/* Footer */}
                <div className="flex justify-end px-5 py-3 border-t border-border">
                    <button
                        onClick={onClose}
                        className="px-4 py-2 rounded-lg bg-surface-3 hover:bg-surface-2 border border-border hover:border-border-bright text-text-muted hover:text-text-primary text-sm font-mono transition-all duration-150"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    );
}
